all: ZeroTask FirstTask SecondTask ThirdTask FourthTask FifthTask SixthTask

ZeroTask: ZeroTask.c
	gcc -c ZeroTask.c
	gcc -o ZeroTask ZeroTask.c -lm
	clear
	rm -rf ZeroTask.o ZeroTask
	
FirstTask: FirstTask.c
	gcc -c FirstTask.c
	gcc -o FirstTask FirstTask.c -lm
	clear
	rm -rf FirstTask.o FirstTask
	
SecondTask: SecondTask.c
	gcc -c SecondTask.c
	gcc -o SecondTask SecondTask.c -lm
	clear
	rm -rf SecondTask.o SecondTask
	
ThirdTask: ThirdTask.c
	gcc -c ThirdTask.c
	gcc -o ThirdTask ThirdTask.c -lm
	clear
	rm -rf ThirdTask.o ThirdTask
	
FourthTask: FourthTask.c
	gcc -c FourthTask.c
	gcc -o FourthTask FourthTask.c -lm
	clear
	rm -rf FourthTask.o FourthTask
	
FifthTask: FifthTask.c
	gcc -c FifthTask.c
	gcc -o FifthTask FifthTask.c -lm
	clear
	rm -rf FifthTask.o FifthTask

SixthTask: SixthTask.c
	gcc -c SixthTask.c
	gcc -o SixthTask SixthTask.c -lm
	clear
	rm -rf SixthTask.o SixthTask
